spring.application.name=jspAndJstl

server.port=9090

spring.security.user.name=progress
spring.security.user.password=progress

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp